### ISSUE TITLE
Pequeño error con link

### ISSUE THREAD

**Issue by GuidoDipietro** [pdepmartestm/presentacion-pmpellegrini7#1]
Hola Pablo, escribo esto sólo a modo de prueba porque el "error" es realmente algo que a nadie le importa.
Donde está el link al video se repite el texto, diciendo algo como
> tengo videos Video tocando la guitarra

Saludos, ya me voy a dormir.

**Comment by pmpellegrini7** [comment]
Hola Guido ya modifique el link.
Cierro Issue.
