### ISSUE TITLE
breaking bad

### ISSUE THREAD

**Issue by gtotaro** [pdepmartestm/presentacion-pmpellegrini7#3]
Hola Pablo, algún capitulo que te haya gustado más? te parece agregarlo...

**Comment by pmpellegrini7** [comment]
Hola Gaston! 
No te respondí antes porque no me aviso por correo que tenia un Issue jaja, ahí agregue a mi presentación uno de mis capítulos favoritos de la serie.

Cierro Issue, 

Saludos!
PD: Me alegro que te haya servido Typora :D
